FROM debian:latest

WORKDIR /app

RUN apt-get update
RUN apt-get install -y curl
RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
RUN chmod u+x nvim.appimage
RUN ./nvim.appimage --appimage-extract
RUN mv squashfs-root / && ln -s /squashfs-root/AppRun /usr/bin/nvim

ENTRYPOINT ["/usr/bin/nvim"]
